import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import * as sass from 'sass';

interface CSSVariable {
  name: string;
  value: string;
  defaultValue: string;
  type: 'color' | 'font' | 'size' | 'number' | 'string';
  category: string;
  description?: string;
}

function detectVariableType(name: string, value: string): CSSVariable['type'] {
  const lowerName = name.toLowerCase();
  const lowerValue = value.toLowerCase();

  if (lowerValue.match(/^#[0-9a-f]{3,8}$/i) || 
      lowerValue.match(/^rgba?\s*\(/) || 
      lowerValue.match(/^hsla?\s*\(/) ||
      lowerName.includes('color') ||
      lowerName.includes('background') ||
      lowerName.includes('foreground') ||
      lowerName.includes('border') && !lowerName.includes('radius') && !lowerName.includes('width')) {
    return 'color';
  }

  if (lowerName.includes('font-family') || lowerName.includes('font-sans') || 
      lowerName.includes('font-serif') || lowerName.includes('font-mono')) {
    return 'font';
  }

  if (lowerValue.match(/^[\d.]+\s*(px|rem|em|%|vh|vw|pt|cm|mm|in)$/i) ||
      lowerName.includes('size') || lowerName.includes('spacing') ||
      lowerName.includes('radius') || lowerName.includes('width') ||
      lowerName.includes('height') || lowerName.includes('padding') ||
      lowerName.includes('margin') || lowerName.includes('gap')) {
    return 'size';
  }

  if (lowerValue.match(/^[\d.]+$/) || 
      lowerName.includes('weight') || lowerName.includes('line-height') ||
      lowerName.includes('opacity') || lowerName.includes('z-index')) {
    return 'number';
  }

  return 'string';
}

function categorizeVariable(name: string): string {
  const lowerName = name.toLowerCase();

  if (lowerName.includes('primary') || lowerName.includes('secondary') || 
      lowerName.includes('accent') || lowerName.includes('brand')) {
    return 'brand-colors';
  }

  if (lowerName.includes('background') || lowerName.includes('foreground') ||
      lowerName.includes('muted') || lowerName.includes('card') ||
      lowerName.includes('border') && !lowerName.includes('radius') && !lowerName.includes('width') ||
      lowerName.includes('input') && !lowerName.includes('height')) {
    return 'neutral-colors';
  }

  if (lowerName.includes('destructive') || lowerName.includes('success') ||
      lowerName.includes('warning') || lowerName.includes('error') ||
      lowerName.includes('info') || lowerName.includes('danger')) {
    return 'status-colors';
  }

  if (lowerName.includes('font') || lowerName.includes('text') ||
      lowerName.includes('line-height') || lowerName.includes('letter') ||
      lowerName.includes('weight')) {
    return 'typography';
  }

  if (lowerName.includes('spacing') || lowerName.includes('gap') ||
      lowerName.includes('margin') || lowerName.includes('padding')) {
    return 'spacing';
  }

  if (lowerName.includes('radius') || lowerName.includes('border-width')) {
    return 'borders';
  }

  if (lowerName.includes('shadow')) {
    return 'shadows';
  }

  if (lowerName.includes('button') || lowerName.includes('input-height') ||
      lowerName.includes('nav') || lowerName.includes('sidebar') ||
      lowerName.includes('card-padding') || lowerName.includes('component')) {
    return 'components';
  }

  if (lowerName.includes('transition') || lowerName.includes('duration') ||
      lowerName.includes('easing') || lowerName.includes('animation')) {
    return 'transitions';
  }

  return 'other';
}

function parseScssVariables(content: string): CSSVariable[] {
  const variables: CSSVariable[] = [];
  
  const cssVarRegex = /--([a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
  let match;
  
  while ((match = cssVarRegex.exec(content)) !== null) {
    const name = `--${match[1]}`;
    const value = match[2].trim();
    const type = detectVariableType(name, value);
    const category = categorizeVariable(name);
    
    variables.push({
      name,
      value,
      defaultValue: value,
      type,
      category,
    });
  }

  const scssVarRegex = /\$([a-zA-Z0-9_-]+)\s*:\s*([^;!]+)(?:\s*!default)?;/g;
  
  while ((match = scssVarRegex.exec(content)) !== null) {
    const name = `--${match[1]}`;
    const value = match[2].trim();
    const type = detectVariableType(name, value);
    const category = categorizeVariable(name);
    
    if (!variables.find(v => v.name === name)) {
      variables.push({
        name,
        value,
        defaultValue: value,
        type,
        category,
      });
    }
  }

  return variables;
}

function generateCss(variables: CSSVariable[], baseScss?: string): string {
  const cssVarsBlock = variables
    .map(v => `  ${v.name}: ${v.value};`)
    .join('\n');

  const modifiedCount = variables.filter(v => v.value !== v.defaultValue).length;

  let css = `/* Theme CSS
 * Generated by Theme Customizer
 * Modified variables: ${modifiedCount}/${variables.length}
 * Generated at: ${new Date().toISOString()}
 */

:root {
${cssVarsBlock}
}
`;

  if (baseScss) {
    try {
      const variableDeclarations = variables
        .map(v => `$${v.name.replace('--', '')}: ${v.value};`)
        .join('\n');

      const scssWithOverrides = variableDeclarations + '\n\n' + baseScss;

      const result = sass.compileString(scssWithOverrides, {
        style: 'expanded',
      });

      css += '\n/* Compiled from base SCSS */\n' + result.css;
    } catch (err) {
      console.error('SCSS compilation error:', err);
    }
  }

  return css;
}

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  
  app.post('/api/parse-scss', async (req, res) => {
    try {
      const { content } = req.body;
      
      if (!content || typeof content !== 'string') {
        return res.status(400).json({ error: 'Content is required' });
      }

      const variables = parseScssVariables(content);
      
      res.json({ 
        success: true, 
        variables,
        count: variables.length 
      });
    } catch (err) {
      console.error('Parse SCSS error:', err);
      res.status(500).json({ error: 'Failed to parse SCSS content' });
    }
  });

  app.post('/api/compile-theme', async (req, res) => {
    try {
      const { variables, baseScss } = req.body;
      
      if (!variables || !Array.isArray(variables)) {
        return res.status(400).json({ error: 'Variables array is required' });
      }

      const css = generateCss(variables, baseScss);
      
      res.json({ 
        success: true, 
        css,
        lineCount: css.split('\n').length
      });
    } catch (err) {
      console.error('Compile theme error:', err);
      res.status(500).json({ error: 'Failed to compile theme' });
    }
  });

  app.get('/api/sample-scss', async (req, res) => {
    const sampleScss = `/* Sample Base SCSS Foundation
 * This is a demonstration of CSS custom properties
 * that can be customized with the Theme Customizer
 */

:root {
  /* Brand Colors */
  --primary: #3B82F6;
  --primary-foreground: #FFFFFF;
  --secondary: #64748B;
  --secondary-foreground: #FFFFFF;
  --accent: #8B5CF6;
  --accent-foreground: #FFFFFF;

  /* Neutral Colors */
  --background: #FFFFFF;
  --foreground: #0F172A;
  --card: #FFFFFF;
  --card-foreground: #0F172A;
  --muted: #F1F5F9;
  --muted-foreground: #64748B;
  --border: #E2E8F0;
  --input: #E2E8F0;

  /* Status Colors */
  --destructive: #EF4444;
  --destructive-foreground: #FFFFFF;
  --success: #22C55E;
  --success-foreground: #FFFFFF;
  --warning: #F59E0B;
  --warning-foreground: #FFFFFF;
  --info: #0EA5E9;
  --info-foreground: #FFFFFF;

  /* Typography */
  --font-family-sans: 'Inter', sans-serif;
  --font-family-serif: 'Georgia', serif;
  --font-family-mono: 'JetBrains Mono', monospace;
  --font-size-base: 16px;
  --font-size-sm: 14px;
  --font-size-lg: 18px;
  --font-size-xl: 20px;
  --font-size-2xl: 24px;
  --font-size-3xl: 30px;
  --line-height-normal: 1.5;
  --line-height-tight: 1.25;
  --line-height-loose: 1.75;
  --font-weight-normal: 400;
  --font-weight-medium: 500;
  --font-weight-semibold: 600;
  --font-weight-bold: 700;

  /* Spacing */
  --spacing-xs: 4px;
  --spacing-sm: 8px;
  --spacing-md: 16px;
  --spacing-lg: 24px;
  --spacing-xl: 32px;
  --spacing-2xl: 48px;
  --spacing-3xl: 64px;

  /* Borders & Radius */
  --radius-sm: 4px;
  --radius-md: 6px;
  --radius-lg: 8px;
  --radius-xl: 12px;
  --radius-full: 9999px;
  --border-width: 1px;
  --border-width-thick: 2px;

  /* Shadows */
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.05);
  --shadow-md: 0 4px 6px rgba(0,0,0,0.1);
  --shadow-lg: 0 10px 15px rgba(0,0,0,0.1);
  --shadow-xl: 0 20px 25px rgba(0,0,0,0.15);

  /* Components */
  --button-height-sm: 32px;
  --button-height-md: 40px;
  --button-height-lg: 48px;
  --input-height: 40px;
  --card-padding: 24px;
  --nav-height: 64px;
  --sidebar-width: 280px;

  /* Transitions */
  --transition-fast: 150ms;
  --transition-normal: 200ms;
  --transition-slow: 300ms;
  --easing-default: ease-in-out;
}

/* Base Styles */
body {
  font-family: var(--font-family-sans);
  font-size: var(--font-size-base);
  line-height: var(--line-height-normal);
  color: var(--foreground);
  background-color: var(--background);
  margin: 0;
  padding: 0;
}

/* Button Styles */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: var(--spacing-sm) var(--spacing-md);
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-medium);
  border-radius: var(--radius-md);
  border: var(--border-width) solid transparent;
  cursor: pointer;
  transition: all var(--transition-normal) var(--easing-default);
}

.btn-primary {
  background-color: var(--primary);
  color: var(--primary-foreground);
}

.btn-primary:hover {
  opacity: 0.9;
}

.btn-secondary {
  background-color: var(--secondary);
  color: var(--secondary-foreground);
}

.btn-outline {
  background-color: transparent;
  border-color: var(--border);
  color: var(--foreground);
}

.btn-outline:hover {
  background-color: var(--muted);
}

/* Card Styles */
.card {
  background-color: var(--card);
  color: var(--card-foreground);
  border: var(--border-width) solid var(--border);
  border-radius: var(--radius-lg);
  padding: var(--card-padding);
  box-shadow: var(--shadow-sm);
}

/* Form Styles */
.input {
  width: 100%;
  height: var(--input-height);
  padding: 0 var(--spacing-sm);
  font-size: var(--font-size-sm);
  border: var(--border-width) solid var(--input);
  border-radius: var(--radius-md);
  background-color: var(--background);
  color: var(--foreground);
  transition: border-color var(--transition-fast) var(--easing-default);
}

.input:focus {
  outline: none;
  border-color: var(--primary);
}

/* Badge Styles */
.badge {
  display: inline-flex;
  align-items: center;
  padding: var(--spacing-xs) var(--spacing-sm);
  font-size: 12px;
  font-weight: var(--font-weight-medium);
  border-radius: var(--radius-full);
}

.badge-success {
  background-color: var(--success);
  color: var(--success-foreground);
}

.badge-warning {
  background-color: var(--warning);
  color: var(--warning-foreground);
}

.badge-destructive {
  background-color: var(--destructive);
  color: var(--destructive-foreground);
}

/* Navigation */
.nav {
  display: flex;
  align-items: center;
  height: var(--nav-height);
  padding: 0 var(--spacing-lg);
  background-color: var(--card);
  border-bottom: var(--border-width) solid var(--border);
}

/* Sidebar */
.sidebar {
  width: var(--sidebar-width);
  background-color: var(--muted);
  border-right: var(--border-width) solid var(--border);
  padding: var(--spacing-md);
}
`;

    res.json({
      success: true,
      content: sampleScss,
      filename: 'sample-theme.scss'
    });
  });

  return httpServer;
}
