import { useState, useMemo } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useToast } from '@/hooks/use-toast';
import { Copy, Download, Check } from 'lucide-react';
import { CSSVariable } from './types';

interface ExportModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  variables: CSSVariable[];
}

export function ExportModal({ open, onOpenChange, variables }: ExportModalProps) {
  const [filename, setFilename] = useState('theme');
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generatedCSS = useMemo(() => {
    const modifiedVars = variables.filter(v => v.value !== v.defaultValue);
    const allVars = variables;

    const scssVarMappings: Record<string, string> = {
      '--color-brand-a': '$color-brand-a',
      '--color-brand-b': '$color-brand-b',
      '--color-brand-c': '$color-brand-c',
      '--color-brand-d': '$color-brand-d',
      '--color-brand-e': '$color-brand-e',
      '--color-brand-f': '$color-brand-f',
      '--color-brand-g': '$color-brand-g',
      '--grid-max-width': '$grid-max-width',
      '--grid-container-max-width': '$grid-max-width',
    };

    const scssVarsToExport = new Map<string, string>();
    
    const gridMaxWidthVar = allVars.find(v => v.name === '--grid-container-max-width') 
      || allVars.find(v => v.name === '--grid-max-width');
    scssVarsToExport.set('$grid-max-width', gridMaxWidthVar?.value || '1240px');
    
    Object.entries(scssVarMappings).forEach(([cssVar, scssVar]) => {
      if (!scssVarsToExport.has(scssVar)) {
        const variable = allVars.find(v => v.name === cssVar);
        const value = variable ? variable.value : '#000000';
        scssVarsToExport.set(scssVar, value);
      }
    });
    
    const scssVarsBlock = Array.from(scssVarsToExport.entries())
      .map(([scssVar, value]) => `${scssVar}: ${value};`)
      .join('\n');

    const cssVarsBlock = allVars
      .map(v => {
        const scssVar = scssVarMappings[v.name];
        if (scssVar) {
          return `  ${v.name}: #{${scssVar}};`;
        }
        return `  ${v.name}: ${v.value};`;
      })
      .join('\n');

    const css = `/* Theme: ${filename}.css
 * Generated by Theme Customizer
 * Modified variables: ${modifiedVars.length}/${variables.length}
 */

// Importing Fundamentals Variables
@import '../../../../../GoBasic/baseStylesV6/css/variables.scss';

/* --- Color by SCSS --- */
${scssVarsBlock}

:root {
${cssVarsBlock}
}

// Importing Fundamentals Styles
@import '../../../../../GoBasic/baseStylesV6/css/imports.scss';
@import '../../../../../GoBasic/baseStylesV6/css/import-html-publication.scss';
`;

    return css;
  }, [variables, filename]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedCSS);
      setCopied(true);
      toast({
        title: 'Copied to clipboard',
        description: 'The CSS has been copied to your clipboard.',
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast({
        title: 'Copy failed',
        description: 'Unable to copy to clipboard. Please try again.',
        variant: 'destructive',
      });
    }
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCSS], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.css`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: 'Download started',
      description: `${filename}.css has been downloaded.`,
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>Export Theme</DialogTitle>
          <DialogDescription>
            Preview and download your generated CSS theme file.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 flex-1 min-h-0">
          <div className="space-y-2">
            <Label htmlFor="filename">Filename</Label>
            <div className="flex items-center gap-2">
              <Input
                id="filename"
                value={filename}
                onChange={(e) => setFilename(e.target.value.replace(/[^a-zA-Z0-9-_]/g, ''))}
                placeholder="theme"
                className="flex-1"
                data-testid="input-export-filename"
              />
              <span className="text-sm text-muted-foreground">.css</span>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Preview</Label>
              <span className="text-xs text-muted-foreground">
                {generatedCSS.split('\n').length} lines
              </span>
            </div>
            <ScrollArea className="h-[300px] border rounded-md">
              <pre className="p-4 text-xs font-mono bg-muted/50 whitespace-pre-wrap" data-testid="text-css-preview">
                {generatedCSS}
              </pre>
            </ScrollArea>
          </div>
        </div>

        <DialogFooter className="flex-shrink-0 gap-2 sm:gap-2">
          <Button variant="outline" onClick={handleCopy} data-testid="button-copy-css">
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-1.5" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-1.5" />
                Copy to Clipboard
              </>
            )}
          </Button>
          <Button onClick={handleDownload} data-testid="button-download-css">
            <Download className="h-4 w-4 mr-1.5" />
            Download
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default ExportModal;
